# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('userid', models.CharField(max_length=30)),
                ('userpw', models.CharField(max_length=30)),
                ('email', models.IntegerField(default=1)),
                ('area_1', models.CharField(max_length=15)),
                ('area_2', models.CharField(max_length=15)),
            ],
        ),
    ]
